### ISSUE TITLE
Allow hundredths of millimeter in bedThickness value for GlassBedCornerAdjustable.scad

### ISSUE THREAD

**Issue by loshlee** [DrLex0/print3d-adjustable-glass-bed-bracket#1]
Suggest "bedThickness = 9.20; //[3:0.01:12]" rather than "bedThickness = 9.2; //[3:0.1:12]" because current doesn't allow setting hundredths of millimeter (you suggest adding .25mm in explanation).

**Comment by DrLex0** [comment]
Hundredths of a millimeter would be pretty pointless considering the accuracy of most 3D printers. I changed it to .05 mm increments which is still realistic.

**Comment by loshlee** [comment]
OK, thanks. I really love the brackets, BTW. Printed them in ABS. Thanks again.

 

Sincerely,

Laine Lee

 

 

On 4/10/21, 7:51 AM, "Alexander Thomas" ***@***.***> wrote:

 

Hundredths of a millimeter would be pretty pointless considering the accuracy of most 3D printers. I changed it to .05 mm increments which is still realistic.
